# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(721, 720)
        self.pushButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 10, 131, 45))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 70, 131, 45))
        self.pushButton_3.setObjectName("pushButton_3")
        # self.pushButton_3.setStyleSheet('background-color: rgb(135, 0, 0); color: rgb(0, 0, 0)')
        self.pushButton_4 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 130, 131, 45))
        self.pushButton_4.setObjectName("pushButton_4")
        # self.pushButton_4.setStyleSheet('background-color: rgb(0, 0, 135); color: rgb(0, 0, 0)')
        self.pushButton_5 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 190, 131, 45))
        self.pushButton_5.setObjectName("pushButton_5")
        # self.pushButton_5.setStyleSheet('background-color: rgb(0, 135, 0); color: rgb(0, 0, 0)')
        self.pushButton_6 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(50, 250, 131, 45))
        self.pushButton_6.setObjectName("pushButton_6")
        # self.pushButton_6.setStyleSheet('background-color: rgb(255, 165, 0); color: rgb(0, 0, 0)')
        self.pushButton_7 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(50, 310, 131, 45))
        self.pushButton_7.setObjectName("pushButton_7")
        # self.pushButton_7.setStyleSheet('background-color: rgb(139, 0, 255); color: rgb(0, 0, 0)')
        self.pushButton_8 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(50, 420, 131, 50))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(50, 490, 131, 50))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_10.setGeometry(QtCore.QRect(50, 560, 131, 50))
        self.pushButton_10.setObjectName("pushButton_10")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_2.setText(_translate("Dialog", "Общий режим"))
        self.pushButton_3.setText(_translate("Dialog", "Красная ветка"))
        self.pushButton_4.setText(_translate("Dialog", "Синяя ветка"))
        self.pushButton_5.setText(_translate("Dialog", "Зелёная ветка"))
        self.pushButton_6.setText(_translate("Dialog", "Оранжевая ветка"))
        self.pushButton_7.setText(_translate("Dialog", "Фиолетовая ветка"))
        self.pushButton_8.setText(_translate("Dialog", "Карта с названиями"))
        self.pushButton_9.setText(_translate("Dialog", "Статистика"))
        self.pushButton_10.setText(_translate("Dialog", "Запомнить попытку"))
